### ISSUE TITLE
Notation P[E_1, E_2] for P[E_1 \cup E_2]

### ISSUE THREAD

**Issue by cschaffner** [BasicProbability/LectureNotes#11]
I do think we should include again this notation in Def 2.4 of joint probability. I think it's quite commonly used and it should be introduced. Do you agree, @philschulz ?
In that case, we could also change back the exercise phrasing...

**Comment by philschulz** [comment]
We can do that. For me, either variant is fine as long as we keep the notation consistent throughout (e.g. we would also have to change the def of conditional probability accordingly).

**Comment by cschaffner** [comment]
I think that both is used, so the students should at least have seen both. I guess it's less confusing to always use \cup, but it's quite common that a "," slips through sometimes...

**Comment by philschulz** [comment]
Alright, then I would just mention P(E1,E2) as an alternative notation in the definition itself. I will add this now. Maybe you can also mention it in the lecture tomorrow.

**Comment by philschulz** [comment]
Hey guys,

homework 2 is done, so I'll just close this thread.
