### ISSUE TITLE
Chapter 3 --- what remains to do

### ISSUE THREAD

**Issue by philschulz** [BasicProbability/LectureNotes#14]
Hey Christian,

I will address your in text comments during this week. Thanks for the input on plotting. I wanted to re-plot the graphs anyway and also add a plot for the cdf. Do you think it makes sense to include the negative Binomial into the distributions section (it's not terribly important but deriving it was one of the homework exercises, so it might be nice to have it in there)?

**Comment by cschaffner** [comment]
Yes, I think that makes sense. We can also \* it or make it not bold, but it's good to know some distributions, also if they are a bit more involved.

**Comment by philschulz** [comment]
Hey Christian,

just to give you an update. I have changed almost everything you pointed out. In addition, I have redone the plots and added a section about the negative binomial. Right now I am fixing the lottery example and then I will make a pull request. It seems like there are going to be some merge issues, though. I hope this will not be too much of a pain. I have an appointment now and will finish up the rest tomorrow. However, I will already make a pull request, so that you can see what I have changed. Please do not accept the request yet, as updating needs to be done.

**Comment by philschulz** [comment]
Ah yeah, 

at some points, I also added inline comments. Please look at those.
