### ISSUE TITLE
errors found by Julia Turska (email to Chris from 15 Nov 2017, 12:17)

### ISSUE THREAD

**Issue by cschaffner** [BasicProbability/LectureNotes#33]
1. On page 27, underneath exercise 3.9, there seems to be a verb missing in the first sentence of the paragraph: It is important to point out that the expectation of a random variable is a real number which does not need to () in the support of X.
2. On page 27, in the top paragraph, there is a sum that seems to be missing an argument:
 
3. In exercise 4.2 on page 42, the second sentence there is a missing ’n': Prove the chain rule for random variables. The proof is totally analogous to the one give for events.
4. On page 47, in the first sentence which starts on that page, there should be ‘life’ instead of ‘live': However, it makes our live much easier because we only have to deal with very simple terms of the form P(Xi = xi|Y = y).
5. On page 52, in the 4th sentence of the 1st paragraph there is a missing article: The sample mean can be seen as guess () of the expectation of Xi
6. On page 55, theorem 5.7 there seems to be a repetition (as in  i.i.d. d. stands for distributed)  : For n ∈ N, let X1n, be i.i.d. distributed random variables with distribution PX

**Comment by bacor** [comment]
I moved the second typo (which I couldn't spot?) to issue #33; resolved the rest.
